---
- hosts: "{{server}}"
  any_errors_fatal: true

  vars_files:
    - vars/configs.yml


  vars:
    - tempDir: "$HOME/atfdir-tmp"
    - dest: "{{tempDir}}/atf-{{atfVersion}}.tar.gz"
    - requirementsDest: "{{tempDir}}/atf-{{atfVersion}}/requirements.txt"
    - venvPath: "/tmp/ATFVENV/"
    - zephSrc: "{{zephCred}}"
    - zephDest: "$HOME/zephCred"

  tasks:

    - name: " Delete temporary directory '{{tempDir}}' if exists "
      file:
        path: "{{tempDir}}"
        state: absent
    - name: " Create temporary directory '{{tempDir}}' "
      file:
        path: "{{tempDir}}"
        state: directory
        mode: 0755

    - name: " Download build 'atf-{{atfVersion}}.tar.gz' from Artifactory server into '{{tempDir}} directory "
      uri:
        validate_certs: no
        url: "{{artifactoryAtfPath}}"
        method: GET
        user: "{{artifactory_user}}"
        password: "{{artifactory_pwd}}"
        return_content: yes
        dest: "{{dest}}"

    - name: " Extract 'atf-{{atfVersion}}.tar.gz' into '{{tempAtfDir}}' directory "
      unarchive:
        src: "{{dest}}"
        dest: "{{tempDir}}"
        remote_src: yes

    - name: " copy zeph credential file to the server "
      copy:
        src: "{{zephSrc}}"
        dest: "{{zephDest}}"
        mode: 0400

    - name: " Create virtualenv '{{venvPath}}' if doesn't exist "
      command: "virtualenv {{venvPath}} -p python3.6 creates={{venvPath}}"

    - name: " Install requirements from {{requirementsDest}}"
      pip:
        virtualenv: "{{venvPath}}"
        requirements: "{{requirementsDest}}"
        state: forcereinstall

    - name: " Deploy ATF project "
      pip:
        virtualenv_site_packages: yes
        name: "file://{{dest}}"
        virtualenv: "{{venvPath}}"

    - name: " test location "
      command: 'pwd'

    - name: " test location "
      command: 'ls -la'

    - name: " Kerberos token refresh "
      command: 'kinit -kt test.keytab test'

    - name: " Delete temporary directory '{{tempDir}}' "
      file:
        path: "{{tempDir}}"
        state: absent