---
- hosts: "{{server}}"

  vars_files:
    - vars/configs.yml

  vars:
    - dest: "{{tempProjectDirectory}}/{{projectArchiveName}}"

  tasks:

    - name: " Delete temporary directory '{{tempProjectDirectory}}' if exists "
      file:
        path: "{{tempProjectDirectory}}"
        state: absent

    - name: " Create temporary directories '{{tempProjectDirectory}}' and '{{tempProjectDirectory}}' "
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - "{{tempProjectDirectory}}"

    - name: " Download project archive '{{projectArchiveName}}' from Artifactory server "
      uri:
        validate_certs: no
        url: "{{artifactoryProjectPath}}"
        method: GET
        user: "{{artifactory_user}}"
        password: "{{artifactory_pwd}}"
        return_content: yes
        dest: "{{dest}}"

    - name: " Extract '{{projectArchiveName}}' into '{{tempProjectDirectory}}' directory "
      unarchive:
        src: "{{dest}}"
        dest: "{{tempProjectDirectory}}"
        remote_src: yes

    - name: " Unset environment variable 'ATF_CONF_FILE' "
      lineinfile:
        dest: $HOME/.bashrc
        regexp: "export ATF_CONF_FILE=*"
        state: absent

    - name: " Set new environment variable 'ATF_CONF_FILE' "
      lineinfile:
        dest: $HOME/.bashrc
        regexp: "export ATF_CONF_FILE=*"
        line: "export ATF_CONF_FILE={{tempProjectDirectory}}/atf-config.yml"
        insertafter: 'EOF'
        state: present

    - name: " Source the .bashrc file to activate environment variable "
      shell: source $HOME/.bashrc executable=/bin/bash

    - name: " Create 'environment.sh' "
      lineinfile:
        create: yes
        state: present
        dest: "{{tempProjectDirectory}}/environment.sh"
        line: '{{item}}'
        mode: 0755
      with_items:
        - '#!/bin/bash'
        - ''
        - 'export PROJECT_ROOT="$( cd -P "$( dirname "$SOURCE" )" && pwd )"'
        - 'export ATF_CONF_FILE="$PROJECT_ROOT/atf-config.yml"'
