---
- hosts: "{{server}}"

  vars_files:
    - vars/configs.yml


  vars:
    - tempDir: "/tmp/{{projectName}}-tmp"
    - dest: "{{tempProjectDirectory}}/{{projectName}}-{{projectVersion}}.tgz"
    - tempDirArch: "{{tempProjectDirectory}}/{{projectName}}-{{projectVersion}}"

  tasks:

    - name: " Delete temporary directory '{{tempProjectDirectory}}' if exists "
      file:
        path: "{{tempProjectDirectory}}"
        state: absent

    - name: " Create temporary directories '{{tempProjectDirectory}}' and '{{tempDirArch}}' "
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - "{{tempProjectDirectory}}"
        - "{{tempDirArch}}"

    - name: " Download project archive '{{projectName}}-{{projectVersion}}.tgz' from Artifactory server "
      uri:
        validate_certs: no
        url: "{{artifactoryProjectPath}}"
        method: GET
        user: "{{artifactory_user}}"
        password: "{{artifactory_pwd}}"
        return_content: yes
        dest: "{{dest}}"

    - name: " Extract '{{projectName}}-{{projectVersion}}.tgz' into {{tempDirArch}} directory "
      unarchive:
        src: "{{dest}}"
        dest: "{{tempDirArch}}"
        remote_src: yes

    - name: " Unset environment variable 'ATF_CONF_FILE' "
      lineinfile:
        dest: $HOME/.bashrc
        regexp: "export ATF_CONF_FILE=*"
        state: absent

    - name: " Set new environment variable 'ATF_CONF_FILE' "
      lineinfile:
        dest: $HOME/.bashrc
        regexp: "export ATF_CONF_FILE=*"
        line: "export ATF_CONF_FILE={{tempDirArch}}/atf-config.yml"
        insertafter: 'EOF'
        state: present

    - name: " Source the .bashrc file to activate environment variable "
      shell: source $HOME/.bashrc executable=/bin/bash

    - name: " Create 'environment.sh' "
      lineinfile:
        create: yes
        state: present
        dest: "{{tempDirArch}}/environment.sh"
        line: '{{item}}'
        mode: 0755
      with_items:
        - '#!/bin/bash'
        - ''
        - 'export PROJECT_ROOT="$( cd -P "$( dirname "$SOURCE" )" && pwd )"'
        - 'export ATF_CONF_FILE="$PROJECT_ROOT/atf-config.yml"'
